### PR TITLE
Fixing Issue #8

### PR DESCRIPTION
**Pull request by s-bauer**
The `Unity.RegistrationByConvention` assembly is marked as `SecurityTransparent`, meaning I cannot add the [SecurityCriticalAttribute](https://msdn.microsoft.com/de-de/library/system.security.securitycriticalattribute(v=vs.110).aspx) at the `GetObjectData` method (or at least it has no effect).

For .NET Framework there is a  `ISafeSerializationData` Interface with which the Serialization can be handled without needing to deal with SecurityPermissions. This is however not supported in .NET Core so I just excluded it using compiler flag. 

I also added a Limited PermissionSet test which is going to run the Serialization/Deserialization process with a very limited permission set.

In addition I fixed the test, so they are executed for all .NET versions. Thanks to @GreenKn1ght and his commit https://github.com/GreenKn1ght/registration-by-convention/commit/538f3e6d8257521c83cf8ca05897654c1881c0d8

Let me know if you have any concerns or questions!

### CODE REVIEW

**Review by ChipsetSV — APPROVED** [review]

**Review by GreenKn1ght — APPROVED** [review]
Looks good to merge.

**Comment by ENikS** [comment]
@s-bauer 
You are creating new exception. Would going back and using [old exception](https://github.com/unitycontainer/registration-by-convention/blob/9589fa545e0b0553cd624e0d4467a74797b1e2d4/src/Exceptions/DuplicateTypeMappingException.cs) solve the problem?
It would probably be better legacy support...

**Comment by s-bauer** [comment]
@ENikS Sorry, but I don't quite understand what you mean

**Comment by ENikS** [comment]
There was old implementation doing what you've implemented (that is what I think, I might be wrong though). I thought you will use that implementation and just fix current build but you implemented new Exception.

I am OK with either approach but keeping legacy support is not a bad thing, don't you think?

**Comment by s-bauer** [comment]
@ENikS Ok, so I'm still using the same exception, just a different way of serializing and deserializing the exception. The other solution would be to either remove the `GetObjectData` completely or remove the `SecurityTransparent` assembly attribute. I think both of them would cause more trouble than the current solution.

**Comment by ENikS** [comment]
Thank you for your help. Perhaps you could take look at other issues?

**Comment by s-bauer** [comment]
@ENikS Sure, now I'm already familiar with the project. You can expect several PRs in the future!

**Pull request merged**
